### PR TITLE
feat: add section 2 video 28 notes

### PR DESCRIPTION
**Pull request by seanho96**
- https://trello.com/c/upLgRuEt
- Hashes
- Accessing keys/values of Hashes
- Looping through Hashes
- String vs Symbol

### CODE REVIEW

**Review by tlkiong — COMMENTED** [review]
Note that the way to create hash is like in JS's JSON format. String as keys with `=>` was the old way.
---
Question:
Given:
```
sample_hash = { "a" => 1, "b" => 2, "c" => 3 }
```
and we do:
```
sample_hash[:a]
```
it will return `1`. How to do that?

**Comment by seanho96** [comment]
We could transform the sample_hash keys from string to symbol first with
```
sample_hash.transform_keys!(&:to_sym)
```

before calling
```
sample_hash[:a]
```

**Comment by tlkiong** [comment]
how about without transforming the keys?

**Comment by seanho96** [comment]
> how about without transforming the keys?

We can use `.with_indifferent_access` in Rails as such:

```
sample_hash.with_indifferent_access[:a]
```

**Review by tlkiong — APPROVED** [review]

**Pull request merged**
